export const skills = [
  "JavaScript",
  "Java",
  "C#",
  "Python",
  "Ruby",
  "PHP",
  "C++",
  "TypeScript",
  "Go",
  "Swift",
  "Kotlin",
  "HTML",
  "CSS",
  "Sass",
  "Less",
  "React",
  "Angular",
  "Vue.js",
  "Next.js",
  "Nuxt.js",
  "Express.js",
  "Node.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "ASP.NET",
  "Laravel",
  "Symfony",
  "Spring Boot",
  "Hibernate",
  "Bootstrap",
  "Material-UI",
  "Tailwind CSS",
  "jQuery",
  "Backbone.js",
  "Ember.js",
  "Meteor",
  "Svelte",
  "Webpack",
  "Gulp",
  "Grunt",
  "Babel",
  "Jest",
  "Mocha",
  "Chai",
  "Jasmine",
  "Karma",
  "Protractor",
  "Cypress",
  "Puppeteer",
  "Selenium",
  "GraphQL",
  "REST APIs",
  "SOAP",
  "Postman",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Firebase",
  "Heroku",
  "Netlify",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "CI/CD",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "Ansible",
  "Chef",
  "Puppet",
  "Terraform",
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "Cassandra",
  "Oracle",
  "SQLite",
  "NoSQL",
  "Graph Databases",
  "Neo4j",
  "Linux",
  "Unix",
  "Windows Server",
  "Nginx",
  "Apache",
  "IIS",
  "Agile",
  "Scrum",
  "Kanban",
  "JIRA",
  "Confluence",
  "Trello",
  "Asana",
  "Slack",
  "Communication Skills",
  "Problem Solving",
  "Teamwork",
  "Time Management",
  "Leadership",
  "Project Management",
  "Object-Oriented Programming",
  "Functional Programming",
  "Design Patterns",
  "MVC",
  "MVVM",
  "Microservices",
  "Serverless Architecture",
  "Test-Driven Development",
  "Behavior-Driven Development",
  "Continuous Integration",
  "Continuous Deployment",
  "Unit Testing",
  "Integration Testing",
  "System Testing",
  "Performance Testing",
  "Security Testing",
  "Load Balancing",
  "Caching",
  "CDN",
  "Responsive Design",
  "Cross-Browser Compatibility",
  "Accessibility",
  "SEO",
  "UX/UI Design",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Figma",
  "Sketch",
  "InVision",
  "Prototyping",
  "Wireframing",
  "User Research",
  "User Testing",
  "Data Structures",
  "Algorithms",
  "Big O Notation",
  "Cloud Computing",
  "DevOps",
  "Networking",
  "HTTP",
  "HTTPS",
  "TLS/SSL",
  "OAuth",
  "JWT",
  "JSON",
  "XML",
  "YAML",
  "CSV",
  "Regular Expressions",
  "Debugging",
  "Profiling",
  "Performance Optimization",
  "Memory Management",
  "Garbage Collection",
  "Concurrency",
  "Multithreading",
  "Event-Driven Programming",
  "Asynchronous Programming",
  "Promises",
  "Async/Await",
  "WebSockets",
  "Service Workers",
  "Progressive Web Apps",
  "Mobile Development",
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter",
  "Xamarin",
  "Ionic",
  "Cordova",
  "Unity",
  "Game Development",
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Data Science",
  "Data Analysis",
  "Data Visualization",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "TensorFlow",
  "PyTorch",
  "Scikit-Learn",
  "Natural Language Processing",
  "Computer Vision",
  "Blockchain",
  "Cryptocurrency",
  "Smart Contracts",
  "Ethereum",
  "Solidity",
  "Hyperledger",
  "IoT",
  "Edge Computing",
  "Cybersecurity",
  "Ethical Hacking",
  "Penetration Testing",
  "Encryption",
  "Authentication",
  "Authorization",
  "OWASP",
  "GDPR",
  "Compliance",
  "Version Control",
  "Shell Scripting",
  "Bash",
  "PowerShell",
  "Command Line",
  "Logging",
  "Monitoring",
  "Splunk",
  "New Relic",
  "Datadog",
  "ELK Stack",
  "Kafka",
  "RabbitMQ",
  "ActiveMQ",
  "MQTT",
  "Event Sourcing",
  "CQRS",
  "Domain-Driven Design",
  "Enterprise Architecture",
  "SOA",
  "WSDL",
  "UML",
  "SysML",
  "Systems Thinking",
  "Business Analysis",
  "Requirements Gathering",
  "Stakeholder Management",
  "Change Management",
  "Risk Management",
  "Business Intelligence",
  "Data Warehousing",
  "ETL",
  "Hadoop",
  "Spark",
  "Hive",
  "Pig",
  "MapReduce",
  "Big Data",
  "R",
  "SAS",
  "SPSS",
  "Tableau",
  "Power BI",
  "QlikView",
  "Google Analytics",
  "Content Marketing",
  "Social Media Marketing",
  "Email Marketing",
  "Copywriting",
  "Technical Writing",
  "Public Speaking",
  "Presentation Skills",
  "Negotiation",
  "Conflict Resolution",
  "Emotional Intelligence",
  "Adaptability",
  "Creativity",
  "Critical Thinking",
  "Innovation",
  "Entrepreneurship",
  "Financial Analysis",
  "Accounting",
  "Budgeting",
  "Forecasting",
  "Supply Chain Management",
  "Logistics",
  "Lean Manufacturing",
  "Six Sigma",
  "Quality Assurance",
  "Automation",
  "Robotics",
  "MATLAB",
  "AutoCAD",
  "3D Modeling",
  "Finite Element Analysis",
  "Project Scheduling",
  "Risk Assessment",
  "Safety Management",
  "Research",
  "Statistical Analysis",
  "Clinical Trials",
  "ISO Standards",
  "Healthcare IT",
  "Telemedicine",
  "Genetics",
  "Physics",
  "Statistics",
  "Economics",
  "Finance",
  "Marketing",
  "Human Resources",
  "Recruitment",
  "Training and Development",
  "Employee Relations",
  "Diversity and Inclusion",
  "Corporate Social Responsibility",
  "Environmental Science",
  "GIS",
  "Urban Planning",
  "Civil Engineering",
  "Mechanical Engineering",
  "Aerospace Engineering",
  "Materials Science",
  "Nanotechnology",
  "Quantum Computing",
  "Virtual Reality",
  "3D Printing",
  "Renewable Energy",
  "Smart Grid",
  "Electric Vehicles",
  "Autonomous Vehicles",
  "Drone Technology",
  "E-commerce",
  "Retail Management",
  "Sales",
  "Lead Generation",
  "SAP",
  "Enterprise Resource Planning",
  "Data Governance",
  "Master Data Management",
  "Content Management",
  "Document Management",
  "Information Security",
  "Digital Forensics",
  "Disaster Recovery",
  "ITIL",
  "PCI DSS",
  "Cloud Security",
  "Threat Modeling",
  "Firewall Management",
  "Antivirus",
  "Malware Analysis",
  "Encryption",
  "Cryptography",
  "Data Privacy",
  "Anonymization",
  "Data Minimization",
  "Consent Management",
  "Privacy Impact Assessment",
  "Vendor Management",
  "Procurement",
  "Process Optimization",
  "Lean Six Sigma",
  "Operational Excellence",
  "Benchmarking",
  "Strategic Planning",
  "Balanced Scorecard",
  "Key Performance Indicators",
  "Change Management",
  "Restructuring",
  "Consulting",
  "Coaching",
  "Training",
  "Workshop Design",
  "E-Learning",
  "Instructional Design",
  "Learning Management Systems",
  "Educational Technology",
  "Gamification",
  "Blended Learning",
  "Virtual Classroom",
  "Video Conferencing",
  "Collaboration Tools",
  "Content Creation",
  "Blogging",
  "Podcasting",
  "Video Production",
  "Photography",
  "Graphic Design",
  "Illustration",
  "Animation",
  "Storyboarding",
  "Editing",
  "Music Production",
  "Event Management",
  "Public Relations",
  "Media Relations",
  "Brand Management",
  "Market Research",
  "Product Management",
  "Product Development",
  "Marketing Strategy",
  "Digital Marketing",
  "Branding",
  "Typography",
  "Print Design",
  "Publishing",
  "Translation",
  "Transcription",
  "Voice-over",
  "Acting",
  "Music",
  "Songwriting",
  "Art History",
  "Museum Studies",
  "Curation",
  "Conservation",
  "Anthropology",
  "Sociology",
  "Psychology",
  "Counseling",
  "Social Work",
  "Non-Profit Management",
  "Fundraising",
  "Grant Writing",
  "Advocacy",
  "Policy Analysis",
  "Government Relations",
  "Public Policy",
  "International Relations",
  "Diplomacy",
  "Conflict Resolution",
  "Human Rights",
  "International Development",
  "Sustainable Development",
  "Disaster Relief",
  "Environmental Conservation",
  "Agriculture",
  "Culinary Arts",
  "Hospitality Management",
  "Tourism",
  "Aviation",
  "Piloting",
  "Logistics Planning",
  "Transportation Management",
  "Warehouse Management",
  "Inventory Control",
  "Legal Research",
  "Litigation",
  "Mediation",
  "Legal Writing",
  "Paralegal Studies",
  "Corporate Law",
  "Tax Law",
  "Notary Public",
  "Regulatory Compliance",
  "Financial Analysis",
  "Investment Banking",
  "Hedge Funds",
  "Portfolio Management",
  "Financial Planning",
  "Insurance",
  "Actuarial Science",
  "Claims Management",
  "Reinsurance",
  "Fraud Detection",
  "Security",
  "Fire Safety",
  "Occupational Health",
  "Environmental Health",
  "Public Health",
  "Biostatistics",
  "Health Promotion",
  "Disease Prevention",
  "Vaccination",
  "Pathology",
  "Radiology",
  "Oncology",
  "Cardiology",
  "Neurology",
  "Psychiatry",
  "Surgery",
  "Dermatology",
  "Pediatrics",
  "Veterinary Medicine",
  "Zoology",
  "Botany",
  "Ecology",
  "Genomics",
  "Bioinformatics",
  "Synthetic Biology",
  "Biomedical Engineering",
  "Tissue Engineering",
  "Regenerative Medicine",
  "Gene Therapy",
  "Nanomedicine",
  "Electronic Health Records",
  "Medical Billing",
  "Healthcare Administration",
  "Medical Ethics",
  "Rehabilitation",
  "Physical Therapy",
  "Occupational Therapy",
  "Music Therapy",
  "Mindfulness",
  "Meditation",
  "Life Coaching",
  "Career Counseling",
  "Student Affairs",
  "Financial Aid",
  "Alumni Relations",
  "Grant Management",
  "Program Evaluation",
  "Impact Assessment",
  "Theory of Change",
  "Project Management",
  "Agile Methodologies",
  "Product Owner",
  "Lean Startup",
  "Service Design",
  "A/B Testing",
  "Conversion Rate Optimization",
  "Customer Experience",
  "Brand Storytelling",
  "Influencer Marketing",
  "Marketing Automation",
  "Customer Relationship Management",
  "Help Desk Management",
  "Customer Support",
  "Ticketing Systems",
  "Asset Management",
  "Configuration Management",
  "Vendor Management",
  "Transportation",
  "Customs Compliance",
  "International Trade",
  "Foreign Exchange",
  "Commodity Trading",
  "Derivatives",
  "Angel Investing",
  "Portfolio Management",
  "Alpha/Beta Analysis",
  "Financial Modeling",
  "Capital Structure",
  "Corporate Finance",
  "Bond Issuance",
  "Structured Finance",
  "Credit Analysis",
  "Financial Regulation",
  "Financial Compliance",
  "Anti-Money Laundering",
  "Fraud Detection",
  "Dispute Resolution",
  "Alternative Dispute Resolution",
  "Policy Development",
  "Advocacy",
  "ESG Reporting",
  "Impact Investing",
  "Sustainability Reporting",
  "Green Building",
  "Environmental Compliance",
  "Climate Change Mitigation",
  "Resilience Planning",
  "Human Rights",
  "Labor Rights",
  "Ethical Sourcing",
  "Volunteerism",
  "Program Evaluation",
  "Statistical Software",
  "Data Visualization",
  "Business Intelligence",
  "ETL",
  "Data Mining",
  "Hadoop",
  "Data Governance",
  "Data Privacy",
  "Information Security",
  "Network Security",
  "SIEM",
  "Penetration Testing",
  "Security Awareness Training",
  "Occupational Health and Safety",
  "Risk Assessment",
  "Ergonomics",
  "Employee Assistance Programs",
  "Employee Engagement",
  "Performance Management",
  "Succession Planning",
  "Change Management",
  "Culture Transformation",
  "Labor Relations",
  "Compensation and Benefits",
  "Payroll Administration",
  "HRIS",
  "Time and Attendance",
  "Talent Acquisition",
  "Training and Development",
  "Instructional Design",
  "HR Analytics",
  "People Analytics",
  "Predictive Analytics",
  "Data Science",
  "Automation",
  "Process Automation",
  "Edge Computing",
  "Blockchain",
  "Cryptocurrencies",
  "Smart Contracts",
  "IoT",
  "Edge Computing",
  "Distributed Computing",
  "Microservices",
  "Containers",
  "Service Mesh",
  "Monitoring",
  "Logging",
  "DevOps",
  "Ansible",
  "Chef",
  "Configuration Management",
  "Release Management",
  "Git",
  "Feature Flags",
  "A/B Testing",
  "Site Reliability Engineering",
  "Database Administration",
  "Data Modeling",
  "Compliance",
  "Data Privacy",
  "Cyber Insurance",
  "Cybersecurity",
  "Governance",
  "Impact Measurement",
  "Sustainability",
  "Carbon Accounting",
  "Energy Efficiency",
  "Water Conservation",
  "Waste Management",
  "Circular Economy",
  "Diversity and Inclusion",
  "Mental Health",
  "Team Building",
  "Interpersonal Skills",
  "Networking",
  "Language Skills",
  "Cross-Cultural Communication",
  "International Business",
  "Localization",
  "Process Improvement",
  "Business Process Reengineering",
  "Innovation Management",
  "Open Innovation",
  "Entrepreneurship",
  "Business Planning",
  "Go-to-Market Strategy",
  "Customer Acquisition",
  "Business Model Innovation",
  "Competitive Strategy",
  "Strategic Planning",
  "Corporate Governance",
  "Stakeholder Engagement",
  "Corporate Social Responsibility",
  "Climate Action",
  "Social Innovation",
  "Inclusive Business",
  "Education Technology",
  "Future of Work",
  "Job Displacement",
  "Reskilling",
  "Remote Work",
  "Productivity Tools",
  "Time Management",
  "Mindset",
  "Habits",
  "Motivation",
  "Creativity",
  "Leadership",
  "Conflict Resolution",
  "Organizational Culture",
  "Employee Relations",
  "Data Protection",
  "Privacy Policies",
  "HRIS",
  "Payroll Systems",
  "HR Analytics",
  "Continuous Improvement",
  "HR Strategy",
  "Organizational Strategy",
  "Stakeholder Management",
  "Digital Marketing",
  "Content Marketing",
  "Affiliate Marketing",
  "Customer Experience Management",
  "Loyalty Programs",
  "Marketing Analytics",
  "Event Marketing",
  "Crisis Management",
  "Reputation Management",
  "Philanthropy",
  "Shared Value",
  "Inclusive Business",
  "Culture Building",
  "Succession Planning",
  "Change Management",
  "Collaboration",
  "Negotiation",
  "Resilience",
  "Work-Life Integration",
  "Growth Mindset",
  "Agility",
  "Data Literacy",
  "Automation",
  "Cybersecurity",
  "Cloud Computing",
  "Internet of Things",
  "Renewable Energy",
  "Smart Cities",
  "Digital Transformation",
  "Innovation Strategy",
  "Startup Ecosystems",
  "Urban Planning",
  "Globalization",
  "International Relations",
  "Disaster Relief",
  "Education",
  "Poverty Alleviation",
  "Human Rights Advocacy",
  "Climate Change Mitigation",
  "Sustainable Agriculture",
  "Zero Waste",
  "Green Finance",
  "Collective Impact",
  "Theory of Change",
  "Policy Advocacy",
  "Knowledge Management",
  "Adaptive Management",
  "Transformation",
  "Partnerships",
  "Trust",
  "Transparency",
  "Values",
  "Vision",
  "Performance",
  "Impact",
];
