import { faker } from "@faker-js/faker";
import { createRepository } from "./repository";
import { BackgroundInsert } from "./schema";

const repository = createRepository();

function seed() {
  const backgrounds: BackgroundInsert[] = Array.from({ length: 10 }, () => {
    return {
      name: faker.person.fullName(),
      title: faker.person.jobType(),
      bio: faker.person.bio(),
      avatarUrl: faker.image.urlLoremFlickr({
        category: "avatar",
        width: 100,
        height: 100,
      }),
      languages: faker.helpers.arrayElements(
        ["English", "Swedish", "Spanish", "French", "German"],
        3,
      ),
      educations: faker.helpers.arrayElements(
        [
          "B.Sc. in Computer Science",
          "M.Sc. in Artificial Intelligence",
          "Ph.D. in Software Engineering",
          "Diploma in Data Science",
          "Certificate in UX Design",
        ],
        2,
      ),
      skills: faker.helpers.arrayElements(skills, 10),
      links: ["https://github.com", "https://linkedin.com/"],
    };
  });
  backgrounds.forEach((background) => {
    repository.add(background);
  });
}

const skills = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Ruby",
  "Go",
  "PHP",
  "Swift",
  "Kotlin",
  "Rust",
  "Scala",
  "Perl",
  "Dart",

  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "Ember.js",
  "Backbone.js",
  "jQuery",
  "Bootstrap",
  "Tailwind CSS",
  "Material-UI",
  "Foundation",
  "Bulma",
  "Semantic UI",
  "Ant Design",

  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Laravel",
  "Spring Boot",
  "ASP.NET Core",
  "Koa.js",
  "NestJS",
  "FastAPI",
  "Hapi.js",
  "Phoenix",
  "Sails.js",
  "Meteor",

  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "SQLite",
  "Redis",
  "Cassandra",
  "OracleDB",
  "MariaDB",
  "Firebase",
  "DynamoDB",
  "Elasticsearch",
  "CouchDB",
  "Neo4j",
  "Firestore",
  "GraphQL",

  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Terraform",
  "Ansible",
  "Puppet",
  "Chef",
  "Jenkins",
  "GitHub Actions",
  "CircleCI",
  "Travis CI",
  "Vagrant",
  "Prometheus",
  "Grafana",

  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Mercurial",
  "SVN",

  "Jenkins",
  "Travis CI",
  "CircleCI",
  "GitHub Actions",
  "GitLab CI",
  "Bamboo",
  "TeamCity",

  "Agile",
  "Scrum",
  "Kanban",
  "TDD",
  "BDD",
  "DDD",
  "CI/CD",
  "Microservices",
  "RESTful APIs",
  "GraphQL",
  "Serverless",
  "Event-Driven Architecture",
  "Design Patterns",
  "Clean Code",
  "Refactoring",

  "VS Code",
  "IntelliJ IDEA",
  "WebStorm",
  "Sublime Text",
  "Atom",
  "Eclipse",
  "PyCharm",
  "Visual Studio",
  "Vim",
  "Emacs",
  "Postman",
  "Insomnia",
  "Figma",
  "Adobe XD",
  "Sketch",

  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Selenium",
  "Puppeteer",
  "JUnit",
  "RSpec",
  "PyTest",
  "Cucumber",
  "Enzyme",
  "TestCafe",

  "GraphQL",
  "WebAssembly",
  "Progressive Web Apps",
  "Responsive Design",
  "SEO",
  "Accessibility (A11y)",
  "Web Security",
  "OAuth",
  "JWT",
  "SASS/SCSS",
  "LESS",
  "Webpack",
  "Babel",
  "ESLint",
  "Prettier",
  "TypeORM",
  "Sequelize",
  "Prisma",
  "Drizzle ORM",
  "Mongoose",
  "ORMs",
  "NoSQL",
  "SQL",
  "Data Modeling",
  "API Design",

  "Logging",
  "Continuous Integration",
  "Continuous Deployment",
  "Infrastructure as Code",
  "Configuration Management",
  "Containerization",
  "Orchestration",
  "Load Balancing",
  "Scaling",
  "Disaster Recovery",
  "High Availability",
  "Machine Learning",
  "Data Science",
  "Artificial Intelligence",
  "Big Data",
  "Blockchain",
  "IoT",
  "AR/VR",
  "Mobile Development",
  "Game Development",
  "Embedded Systems",
  "Cybersecurity",
  "DevSecOps",
  "Data Engineering",
  "Business Intelligence",
  "Data Visualization",
];

seed();
