export const db = [
  {
    title: "Refactor Authentication",
    link: "https://github.com/user/auth-refactor",
    commits: 56,
    issues: 15,
    duration: "2 weeks",
    performance: 56,
    tests: 1,
  },
  {
    title: "Improve API Performance",
    link: "https://github.com/user/api-performance",
    commits: 78,
    issues: 12,
    duration: "3 weeks",
    performance: 64,
    tests: 5,
  },
  {
    title: "Redesign UI Components",
    link: "https://github.com/user/ui-redesign",
    commits: 45,
    issues: 8,
    duration: "1 week",
    performance: 70,
    tests: 2,
  },
  {
    title: "Add CI/CD Pipeline",
    link: "https://github.com/user/ci-cd-pipeline",
    commits: 102,
    issues: 25,
    duration: "1 month",
    performance: 85,
    tests: 10,
  },
  {
    title: "Fix Critical Bugs",
    link: "https://github.com/user/bug-fixes",
    commits: 30,
    issues: 3,
    duration: "1 week",
    performance: 50,
    tests: 0,
  },
  {
    title: "Optimize Database Queries",
    link: "https://github.com/user/db-optimization",
    commits: 60,
    issues: 7,
    duration: "2 weeks",
    performance: 58,
    tests: 3,
  },
  {
    title: "Implement User Dashboard",
    link: "https://github.com/user/user-dashboard",
    commits: 90,
    issues: 18,
    duration: "3 weeks",
    performance: 76,
    tests: 7,
  },
  {
    title: "Migrate to New Framework",
    link: "https://github.com/user/framework-migration",
    commits: 150,
    issues: 30,
    duration: "1 month",
    performance: 92,
    tests: 15,
  },
  {
    title: "Setup Logging and Monitoring",
    link: "https://github.com/user/log-monitoring",
    commits: 20,
    issues: 5,
    duration: "5 days",
    performance: 40,
    tests: 1,
  },
  {
    title: "Enhance Security Features",
    link: "https://github.com/user/security-enhancements",
    commits: 85,
    issues: 10,
    duration: "2 weeks",
    performance: 68,
    tests: 6,
  },
];

export type Db = typeof db;
